#sudo docker run -p 8181:8181 --name opa-ebpf openpolicyagent/opa run --server --log-level debug
version: '3'
services:
  opa-ebpf:
    image: openpolicyagent/opa
    container_name: opa_basic
    command: run --server --log-level debug
    ports:
      - 8181:8181
