version: '3'
services:
  opa-eval:
    image: openpolicyagent/opa
    container_name: opa_stored_policy
    volumes:
      - ./ebpf:/example
    #stdin_open: true 
    #tty: true
    command: run --server --log-level debug /example
    #command: run --server /example/policy.rego --set data.file=/example/persona_opa.json --log-level debug
    ports:
      - 8181:8181
